### ISSUE TITLE
HONEYPOT ERROR

### ISSUE THREAD

**Issue by pr0gr35528** [UltimateHackers/Striker#27]
i'm running striker.py and i found error in line... how to fix this error.. please help me

**Traceback (most recent call last):
  File "striker.py", line 232, in <module>
    honeypot(ip_addr)
  File "striker.py", line 125, in honeypot
    phoney = br.open(honey).read()
  File "/usr/lib/python2.7/dist-packages/mechanize/_mechanize.py", line 203, in open
    return self._mech_open(url, data, timeout=timeout)
  File "/usr/lib/python2.7/dist-packages/mechanize/_mechanize.py", line 230, in _mech_open
    response = UserAgentBase.open(self, request, data)
  File "/usr/lib/python2.7/dist-packages/mechanize/_opener.py", line 193, in open
    response = urlopen(self, req, data)
  File "/usr/lib/python2.7/dist-packages/mechanize/_urllib2_fork.py", line 344, in _open
    '_open', req)
  File "/usr/lib/python2.7/dist-packages/mechanize/_urllib2_fork.py", line 332, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/dist-packages/mechanize/_urllib2_fork.py", line 1170, in https_open
    return self.do_open(conn_factory, req)
  File "/usr/lib/python2.7/dist-packages/mechanize/_urllib2_fork.py", line 1118, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:661)>_****

**Comment by pr0gr35528** [comment]
i'm running striker.py and i found error in line... how to fix this error.. please help me

**Comment by UltimateHackers** [comment]
Its an error caused by the dependencies or the website itself, not the Striker.
Try using http:// instead of https:// or vice versa.
If that doesn't fixes the issue, maybe SSL has been configured improperly on the website.

**Comment by xillwillx** [comment]
im getting same error with either http or https, should add some error checking 

`[?] Would you like to use WPScan? [Y/n] n
Traceback (most recent call last):
  File "striker.py", line 252, in <module>
    honeypot(ip_addr)
  File "striker.py", line 137, in honeypot
    phoney = br.open(honey).read()
  File "/usr/lib/python2.7/dist-packages/mechanize/_mechanize.py", line 203, in open
    return self._mech_open(url, data, timeout=timeout)
  File "/usr/lib/python2.7/dist-packages/mechanize/_mechanize.py", line 255, in _mech_open
    raise response
mechanize._response.httperror_seek_wrapper: HTTP Error 404: Not Found`

**Comment by thehappydinoa** [comment]
I will look into this

**Comment by RicardoGeek** [comment]
this url: https://api.shodan.io/labs/honeyscore/ 
resets the connection, that is why it fails. Is this a private service?
