### ISSUE TITLE
Cant start

### ISSUE THREAD

**Issue by robertjriga** [UltimateHackers/Striker#31]
Traceback (most recent call last):
  File "striker.py", line 10, in <module>
    from plugins.DNSDumpsterAPI import DNSDumpsterAPI
  File "/opt/Striker/plugins/DNSDumpsterAPI.py", line 12, in <module>
    from bs4 import BeautifulSoup
  File "/usr/local/lib/python2.7/dist-packages/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/usr/local/lib/python2.7/dist-packages/bs4/builder/__init__.py", line 314, in <module>
    from . import _html5lib
  File "/usr/local/lib/python2.7/dist-packages/bs4/builder/_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'

**Comment by UltimateHackers** [comment]
Striker isn't compatible with python3.
