### ISSUE TITLE
SSL 

### ISSUE THREAD

**Issue by geekfrom90s** [UltimateHackers/Striker#5]
this is the second ssl failed verify. 

Traceback (most recent call last):
File "striker", line 185, in
cms(domain)
File "striker", line 74, in cms
result = br.open('https://whatcms.org/?s='+domain).read()
File "/usr/local/lib/python2.7/dist-packages/mechanize/_mechanize.py", line 254, in open
return self._mech_open(url_or_request, data, timeout=timeout)
File "/usr/local/lib/python2.7/dist-packages/mechanize/_mechanize.py", line 284, in _mech_open
response = UserAgentBase.open(self, request, data)
File "/usr/local/lib/python2.7/dist-packages/mechanize/_opener.py", line 195, in open
response = urlopen(self, req, data)
File "/usr/local/lib/python2.7/dist-packages/mechanize/_urllib2_fork.py", line 352, in _open
'_open', req)
File "/usr/local/lib/python2.7/dist-packages/mechanize/_urllib2_fork.py", line 340, in _call_chain
result = func(*args)
File "/usr/local/lib/python2.7/dist-packages/mechanize/_urllib2_fork.py", line 1215, in https_open
return self.do_open(conn_factory, req)
File "/usr/local/lib/python2.7/dist-packages/mechanize/_urllib2_fork.py", line 1160, in do_open
raise URLError(err)
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)>

**Comment by UltimateHackers** [comment]
Looks like you are the only one facing this problem.

**Comment by jslirola** [comment]
I got another error related with SSL:

![ssl_error](https://user-images.githubusercontent.com/6697559/32439266-4d9918ca-c2ee-11e7-9084-dfb5ee8daf7c.JPG)

In plain text: 
`urllib2.URLError: <urlopen error [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handhsake failure>`

**Comment by UltimateHackers** [comment]
[Fixed]
