### ISSUE TITLE
Cloudflare DNS error?

### ISSUE THREAD

**Issue by hollerith** [UltimateHackers/Striker#7]
```   _________ __          __ __
  /   _____//  |________|__|  | __ ___________
  \_____  \\   __\_  __ \  |  |/ // __ \_  __ \
  /        \|  |  |  | \/  |    <\  ___/|  | \/
 /_______  /|__|  |__|  |__|__|_ \\___  >__|
         \/                     \/    \/
[?] Enter the target: 104.27.149.207
[!] IP Address : 104.27.149.207
[!] 104.27.149.207 doesn't seem to use a CMS
[+] Honeypot Probabilty: 0%
----------------------------------------
PORT     STATE    SERVICE       VERSION
21/tcp   filtered ftp
22/tcp   filtered ssh
23/tcp   filtered telnet
25/tcp   filtered smtp
80/tcp   open     http          Cloudflare nginx
110/tcp  filtered pop3
143/tcp  filtered imap
443/tcp  open     ssl/https?
445/tcp  filtered microsoft-ds
3389/tcp filtered ms-wbt-server
----------------------------------------
There was an error getting results

[+] DNS Records
Traceback (most recent call last):
  File "striker.py", line 222, in <module>
    dnsdump(domain)
  File "striker.py", line 158, in dnsdump
    for entry in res['dns_records']['dns']:
TypeError: list indices must be integers, not str
```

**Comment by hollerith** [comment]
So DNSDumpster returns empty array sometimes but it isn't handled res == [] I changed it to check/return.

**Comment by hollerith** [comment]
Argh - just realized my bad sorry - very i5red. ipaddress instead of DN. Not an issue.
